routes/web.php
<?php

use App\Http\Controllers\PersonaControlador;
use App\Http\Controllers\NegocioControlador;
use App\Http\Controllers\TareaControlador;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::controller(PersonaControlador::class)->prefix('persona')->name('persona')->middleware('auth')->group(function () {
    Route::get('/', 'index')->name('.index');
    Route::get('/create', 'create')->name('.create');
    Route::post('/store', 'store')->name('.store');
    Route::get('/{persona}/show', 'show')->name('.show');
    Route::get('/{persona}/edit', 'edit')->name('.edit');
    Route::put('/{persona}/update', 'update')->name('.update');
    Route::delete('/{persona}/destroy', 'destroy')->name('.destroy');
});

Route::controller(NegocioControlador::class)->prefix('negocio')->name('negocio')->middleware('auth')->group(function () {
    Route::get('/', 'index')->name('.index');
    Route::get('/create', 'create')->name('.create');
    Route::post('/store', 'store')->name('.store');
    Route::get('/{negocio}/show', 'show')->name('.show');
    Route::get('/{negocio}/edit', 'edit')->name('.edit');
    Route::put('/{negocio}/update', 'update')->name('.update');
    Route::delete('/{negocio}/destroy', 'destroy')->name('.destroy');
});

Route::controller(TareaControlador::class)->prefix('tarea')->name('tarea')->middleware('auth')->group(function () {
    Route::get('/', 'index')->name('.index');
    Route::post('/store', 'store')->name('.store');
    Route::put('/{tarea}/complete', 'complete')->name('.complete');
});

require __DIR__ . '/auth.php';

app/Models/Negocio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

class Negocio extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
      'negocio_nombre',
      'negocio_correo',
      'negocio_telefono'
    ];

    public function personas() {
        return $this->hasMany(Persona::class);
    }

    public function categorias() {
        return $this->belongsToMany(NegocioCategoria::class, 'categoria_tiene_negocio');
    }

    public function tareas() {
        return $this->morphMany(Tarea::class, 'asignable');
    }

    public function tags() {
        return $this->morphToMany(Tag::class, 'taggable');
    }
}

app/Http/Controllers/NegocioControlador.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NegocioRequest;
use App\Models\Negocio;
use App\Models\Tag;
use Illuminate\Http\Request;

class NegocioControlador extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('negocio.index')->with(['negocios' => Negocio::withCount('personas')->paginate(10), 'tags' => Tag::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('negocio.create')->with(['tags' => Tag::all()]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(NegocioRequest $request)
    {
        $negocio = Negocio::create(($request->validated()));

        return redirect(route('negocio.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Negocio $negocio)
    {
        return view('negocio.detail')->with('negocio', $negocio);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Negocio $negocio)
    {
        return view('negocio.edit')->with(['negocio' => $negocio, 'tags' => Tag::all()]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(NegocioRequest $request, Negocio $negocio)
    {
        $negocio->update($request->validated());

        $negocio->tags()->sync($request->input('tags'));

        return redirect(route('negocio.index'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Negocio $negocio)
    {
        $negocio->delete();

        return redirect(route('negocio.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/negocio/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Negocio') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <h3 class="font-semibold pb-5">Crear Negocio</h3>
                    <form action="{{route('negocio.store')}}" method="POST">
                        @csrf
                        @if($errors->any())
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        @endif

                        <div class="grid grid-cols-1 sm:grid-cols-6 gap-6">
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_nombre">Nombre</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_nombre" id="negocio_nombre" value="{{old('negocio_nombre')}}">
                            </span>
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_correo">Correo</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_correo" id="negocio_correo" value="{{old('negocio_correo')}}">
                            </span>
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_telefono">Telefono</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_telefono" id="negocio_telefono" value="{{old('negocio_telefono')}}">
                            </span>
                        </div>
                        <div class="flex items-center justify-end gap-6 mt-6">
                            <a href="{{route('negocio.index')}}">Cancelar</a>
                            <button class="bg-blue-600 text-white py-2 px-6 rounded-full" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/negocio/detail.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Negocio') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="grid grid-cols-1 sm:grid-cols-6 gap-6">
                        <div class="sm:col-span-3">
                            <h3 class="font-semibold text-l pb-5">Detalles del Negocio</h3>
                            <dl>
                                <dt class="font-semibold">Nombre del Negocio</dt>
                                <dd class="pl-3">{{$negocio->negocio_nombre}}</dd>
                                <dt class="font-semibold">Correo Electrónico</dt>
                                <dd class="pl-3">{{$negocio->negocio_correo}}</dd>
                                <dt class="font-semibold">Número de Teléfono</dt>
                                <dd class="pl-3">{{$negocio->negocio_telefono}}</dd>
                            </dl>
                            <div class="pt-3">
                                <a href="{{route('negocio.edit', $negocio->id)}}" class="bg-blue-500 hover:bg-blue-600 py-2 px-3 rounded-full text-white">Editar Datos</a>
                            </div>
                        </div>
                        <div class="sm:col-span-3">
                            <h3 class="text-l font-semibold pb-5">Crear Nueva Tarea</h3>
                            <form action="{{route('tarea.store')}}" method="POST">
                                @csrf
                                <input type="hidden" name="asignable_id" value="{{$negocio->id}}">
                                <input type="hidden" name="target_model" value="negocio">
                                <div class="grid grid-cols-1 sm:grid-cols-6 gap-6">
                                    <span class="sm:col-span-6">
                                        <label class="block" for="titulo">Titulo</label>
                                        <input class="block w-full" type="text" name="titulo" id="titulo" value="{{old('titulo')}}">
                                    </span>
                                    <span class="sm:col-span-6">
                                        <label class="block" for="descripcion">Descripcion</label>
                                        <textarea class="block w-full" name="descripcion" id="descripcion" cols="30" rows="10">{{old('descripcion')}}</textarea>
                                    </span>
                                </div>
                                <div class="mt-5 flex items-center justify-end gap-6">
                                    <button class="flex items-center justify-end ml-2 bg-blue-500 hover:bg-blue-600 text-white px-3 py-2 rounded-full" type="submit">Guardar</button>
                                </div>
                            </form>
                            <h3 class="text-l font-semibold pb-5">Tareas</h3>
                            @foreach($negocio->tareas->sortByDesc('created_at') as $tarea)
                                <p class="font-semibold">{{$tarea->titulo}}</p>
                                <p>{{$tarea->descripcion}}</p>
                                @if($tarea->status == 'open')
                                    <div class="pt-3">
                                        <form action="{{route('tarea.complete', $tarea->id)}}" method="POST">
                                            @csrf
                                            @method('PUT')
                                            <button class="bg-blue-100 hover:bg-blue-200 text-blue-500 rounded-full py-2 px-3" type="submit">Completar</button>
                                        </form>
                                    </div>
                                @elseif($tarea->status == 'completed')
                                    <p>Completed</p>
                                @endif
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/negocio/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Negocio') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <h3 class="font-semibold pb-5">Editar Negocio</h3>
                    <form action="{{route('negocio.update', $negocio->id)}}" method="POST">
                        @csrf
                        @method('PUT')
                        @if($errors->any())
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        @endif

                        <div class="grid grid-cols-1 sm:grid-cols-6 gap-6">
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_nombre">Nombre</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_nombre" id="negocio_nombre" value="{{old('negocio_nombre', $negocio->negocio_nombre)}}">
                            </span>
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_correo">Correo</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_correo" id="negocio_correo" value="{{old('negocio_correo', $negocio->negocio_correo)}}">
                            </span>
                            <span class="sm:col-span-3">
                                <label class="block" for="negocio_telefono">Telefono</label>
                                <input class="block w-full rounded-md" type="text" name="negocio_telefono" id="negocio_telefono" value="{{old('negocio_telefono', $negocio->negocio_telefono)}}">
                            </span>
                        </div>

                        <h4 class="font-semibold pt-5">Etiquetas</h4>
                        <div class="grid grid-cols-1 sm:grid-cols-12 gap-6">
                            @foreach($tags as $tag)
                                <span class="sm:col-span-2">
                                    <input type="checkbox" name="tags[]" id="tag{{$tag->id}}" value="{{$tag->id}}" @checked(in_array($tag->tag_name, $negocio->tags->pluck('tag_name')->toArray()))>
                                    <label for="tag{{$tag->id}}">{{$tag->tag_name}}</label>
                                </span>
                            @endforeach
                        </div>

                        <div class="flex items-center justify-end gap-6 mt-6">
                            <a href="{{route('negocio.index')}}">Cancelar</a>
                            <button class="bg-blue-600 hover:bg-blue-700 text-white py-2 px-6 rounded-full" type="submit">Editar</button>
                        </div>
                    </form>

                    <form action="{{route('negocio.destroy', $negocio->id)}}" method="POST">
                        @csrf
                        @method('DELETE')

                        <div class="border border-red-500 text-white bg-red-500 mt-6 p-6 rounded-lg">
                            <div class="flex justify-between">
                                <h3 class="font-semibold">Eliminar este negocio</h3>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                                </svg>

                            </div>
                            <p>Esta acción elimina el negocio {{ $negocio->negocio_nombre }} de la base de datos. <strong class="text-black">No hay vuelta atrás.</strong></p>
                            <button type="submit" class="hover:text-black">Eliminar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/negocio/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Negocio') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <div class="flex items-center justify-end">
                        <a class="bg-blue-600 text-white  py-2 px-3 rounded-full" href="{{route('negocio.create')}}">Crear Negocio</a>
                    </div>
                    <table class="table-fixed border-separate border-spacing-6 text-sm">
                        <thead>
                            <tr>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Nombre</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Correo</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Teléfono</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Categorias</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Etiquetas</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Total Empleados</th>
                                <th class="border-b dark:border-slate-600 font-medium pt-0 pb-3 text-left">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($negocios as $negocio)
                            <tr>
                                <td>
                                    <a href="{{route('negocio.show', $negocio)}}">{{ $negocio->negocio_nombre }}</a>
                                </td>
                                <td>{{ $negocio->negocio_correo }}</td>
                                <td>{{ $negocio->negocio_telefono }}</td>
                                <td>
                                    @foreach($negocio->categorias as $cat)
                                        {{$cat->categoria_nombre}} <br/>
                                    @endforeach
                                </td>
                                <td>
                                    @foreach($negocio->tags as $tag)
                                        <span class="text-xs inline-flex items-center font-bold leading-sm uppercase px-3 py-1 bg-blue-200 text-blue-700 rounded-full my-1">{{$tag->tag_name}}</span>
                                    @endforeach
                                </td>
                                <td>
                                    {{$negocio->personas_count}}
                                </td>
                                <td>
                                    <a href="{{route('negocio.edit', $negocio->id)}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{$negocios->links()}}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>